module.exports ={
    watchListobj:[{
        '$lookup':{
            'foreignField':'_id',
             'localField': 'categoryId',
             'from':'adminactions',
             'as':'catgorydetails'
        }
    },
    {$unwind:'$catgorydetails'},
    {
        '$project':{
            '_id':1,
            'status':1,
            'watchObj':1,
            'watchItemId':1,
            'userId':1,
            'catgorydetails.name':1,
            'catgorydetails._id':1
        }
    },{
        '$lookup':{
            'foreignField':'_id',
             'localField': 'userId',
             'from':'users',
             'as':'userDetails'
        }
    },
    {$unwind:'$userDetails'},
    {
        '$project':{
            '_id':1,
            'status':1,
            'watchObj':1,
            'watchItemId':1,
            'catgorydetails.name':1,
            'catgorydetails._id':1,
            'userDetails.fullName':1,
            'userDetails._id':1
        }
    }]
}